#!/bin/bash

echo "🚀 RAILWAY DEPLOYMENT SCRIPT FOR ANAND KUMAR PORTFOLIO"
echo "=================================================="
echo ""
echo "Step 1: Create a new GitHub repository"
echo "Step 2: Upload the backend folder to GitHub"
echo "Step 3: Connect Railway to your GitHub repository"
echo ""
echo "Files ready for deployment:"
echo "✅ backend/server.py - Production FastAPI server"
echo "✅ backend/Dockerfile - Container configuration"
echo "✅ backend/requirements.txt - Python dependencies"
echo "✅ railway.json - Railway deployment config"
echo ""
echo "Environment variables needed in Railway:"
echo "MONGO_URL=your_mongodb_connection_string_from_step1"
echo "DB_NAME=portfolio"
echo "PORT=8000"
echo ""
echo "Deploy URL will be: https://your-app-name.up.railway.app"